force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RH_Role__c</field>
            <operation>equals</operation>
            <value>CEO, Team Leader</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Manager</relationshipLabel>
    <relationshipName>Projects_Leaded</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Participation__c/RH_Participation__c.object-meta.xml
<CustomObject>
    <label>Participation</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Participation__c/fields/RH_Contact__c.field-meta.xml
<CustomField>
    <fullName>RH_Contact__c</fullName>
    <label>Contact ID</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RH_Participation__c/fields/RH_Project__c.field-meta.xml
<CustomField>
    <fullName>RH_Project__c</fullName>
    <label>Project ID</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RH_Project_Query.cls
public with sharing class RH_Project_Query {
    /** The class instance */
    private static RH_Project_Query instance = null;

     /**
     * @description @return the class instance
     */
    public static RH_Project_Query getInstance() {

        if(instance == null) {

            instance = new RH_Project_Query();
        }
        return instance;
    }

    public List<Project__c> getProject(){
        return [SELECT id, Name, Description__c,End_Date__c,Link__c,Status__c,Start_Date__c,Project_Manager__r.Name,Project_Manager__c FROM Project__c ];
    }

    public List<Project__c> getProjectById(String IdProject){
        return [SELECT id, Name, Description__c,End_Date__c,Link__c,Status__c,Start_Date__c,Project_Manager__r.Name,Project_Manager__c FROM Project__c WHERE Id =:IdProject];
    }

    public List<RH_Participation__c> getMembers(String IdProject){
        return [SELECT id, RH_Contact__r.Name,RH_Contact__r.Email FROM RH_Participation__c WHERE RH_Project__c = :IdProject];
    }

    public List<RH_Participation__c> getParticipate(List<String> contactId){
        return [SELECT id, RH_Contact__c,RH_Project__c FROM RH_Participation__c WHERE RH_Contact__c IN :contactId];
    }

    public List<Contact> getNotMembers(String IdProject,String Idmanager){
        List<RH_Participation__c> ldt= [SELECT id, RH_Contact__c FROM RH_Participation__c WHERE RH_Project__c = :IdProject or RH_Contact__c = :Idmanager];
        // List<RH_Participation__c> ldt= getMembers(IdProject);
        List<String> lstr = new List<String>();
        for (RH_Participation__c vare : ldt) {
            lstr.add(vare.RH_Contact__c);
        }
        return [SELECT id, Name,Email FROM Contact WHERE Id NOT IN :lstr AND recordTypeId=:RH_Constans.RH_CONTACT_RT];
    }
}