force-app/main/default/objects/NL_Logs__c/NL_Logs__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>logId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NL_Logs__c/fields/NL_Communication__c.field-meta.xml
<CustomField>
    <fullName>NL_Communication__c</fullName>
    <label>Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_CommunicationDirection__c.field-meta.xml
<CustomField>
    <fullName>NL_CommunicationDirection__c</fullName>
    <label>Communication Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN</fullName>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>OUT</fullName>
                <label>Outbound</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_Error__c.field-meta.xml
<CustomField>
    <fullName>NL_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_RecordId__c.field-meta.xml
<CustomField>
    <fullName>NL_RecordId__c</fullName>
    <label>Record ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_Request__c.field-meta.xml
<CustomField>
    <fullName>NL_Request__c</fullName>
    <label>Request</label>
    <length>130999</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_Responce__c.field-meta.xml
<CustomField>
    <fullName>NL_Responce__c</fullName>
    <label>Response</label>
    <length>130999</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_Service__c.field-meta.xml
<CustomField>
    <fullName>NL_Service__c</fullName>
    <label>Service Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NL_Logs__c/fields/NL_Sytems__c.field-meta.xml
<CustomField>
    <fullName>NL_Sytems__c</fullName>
    <label>Systems Involved</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Settings__c/RH_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RH Settings</label>
</CustomObject>

force-app/main/default/objects/RH_Settings__c/fields/NL_SaveLogs__c.field-meta.xml
<CustomField>
    <fullName>NL_SaveLogs__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Save Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RH_Logs_Utility.cls
public without sharing class RH_Logs_Utility {

    public static final  RH_Settings__c cs = RH_Settings__c.getOrgDefaults();
    public static boolean saveLogs = cs.NL_SaveLogs__c;
    private static final Integer STR_LENGTH = 130999;
    
    public static List<NL_Logs__c> saveLogs(List<NL_Logs__c> logs){
        Boolean toInsert= saveLogs!=null && saveLogs ;
        if (saveLogs) {
            insert logs;
        }
        return logs;
    }

    public static NL_Logs__c writeLog(String request, String response, String dirCom, String service, Boolean error, List<String> sistemi, Boolean soap, String IdRecord) {
        Boolean toInsert= saveLogs!=null && saveLogs ;
        return createLog(toInsert, request, response, dirCom, service, error, sistemi, soap, IdRecord);
    }
    public static NL_Logs__c prepareLog(String request, String response, String dirCom, String service, Boolean error, List<String> sistemi, Boolean soap, String IdRecord) {

        return createLog(false, request, response, dirCom, service, error, sistemi, soap, IdRecord);
    }
    private static NL_Logs__c createLog(boolean toInsert,String request, String response, String dirCom, String service, Boolean error, List<String> sistemi, Boolean soap, String IdRecord) {

        NL_Logs__c log = new NL_Logs__c();

        //if(soap) request = (String)JSON.deserializeUntyped(request);
        if(request.length()>STR_LENGTH)  log.NL_Request__c = request.substring(0, STR_LENGTH);
        else log.NL_Request__c = request;
        
        if(response.length()>STR_LENGTH) log.NL_Responce__c = response.substring(0, STR_LENGTH);
        else log.NL_Responce__c = response;
        
        log.NL_CommunicationDirection__c = dirCom;
		log.NL_Service__c = service;
		log.NL_RecordId__c = IdRecord;

        log.NL_Sytems__c = (sistemi.isEmpty()) ? '' : String.join(sistemi, ',');

        if(error) log.NL_Error__c = true;

        if(soap == true) {
            log.NL_Communication__c = 'SOAP';
        } else {
            log.NL_Communication__c = 'REST';
        }
        System.debug('###########log > ' + log);
        if (toInsert) {
            insert log;
        }
        return log;
    }

}