force-app/main/default/objects/Account/fields/RH_Cap__c.field-meta.xml
<CustomField>
    <fullName>RH_Cap__c</fullName>
    <label>Cap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_Citta__c.field-meta.xml
<CustomField>
    <fullName>RH_Citta__c</fullName>
    <label>Citta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_Email__c.field-meta.xml
<CustomField>
    <fullName>RH_Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_NumeroCivico__c.field-meta.xml
<CustomField>
    <fullName>RH_NumeroCivico__c</fullName>
    <label>RH Numero Civico</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_Piva__c.field-meta.xml
<CustomField>
    <fullName>RH_Piva__c</fullName>
    <label>Plva/CF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_Regione__c.field-meta.xml
<CustomField>
    <fullName>RH_Regione__c</fullName>
    <label>Regione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_SDI__c.field-meta.xml
<CustomField>
    <fullName>RH_SDI__c</fullName>
    <label>SDI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RH_Via__c.field-meta.xml
<CustomField>
    <fullName>RH_Via__c</fullName>
    <label>RH Via</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/generatpageHeader__mdt/generatpageHeader__mdt.object-meta.xml
<CustomObject>
    <label>generatpageHeader</label>
    <pluralLabel>generatpageHeader</pluralLabel>
</CustomObject>

force-app/main/default/objects/generatpageHeader__mdt/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>CompanyId</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/generatpageHeader__mdt/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>CompanyName</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/generatpageHeader__mdt/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/generatpageHeader__mdt/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/generatpageHeader__mdt/fields/PoBox__c.field-meta.xml
<CustomField>
    <fullName>PoBox__c</fullName>
    <label>PoBox</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/generatpageHeader__mdt/fields/TaxId__c.field-meta.xml
<CustomField>
    <fullName>TaxId__c</fullName>
    <label>TaxId</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceFooter__mdt/InvoiceFooter__mdt.object-meta.xml
<CustomObject>
    <label>InvoiceFooter</label>
    <pluralLabel>InvoiceFooters</pluralLabel>
</CustomObject>

force-app/main/default/objects/InvoiceFooter__mdt/fields/Acct_No_with_UBA__c.field-meta.xml
<CustomField>
    <fullName>Acct_No_with_UBA__c</fullName>
    <label>Acct No with UBA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceFooter__mdt/fields/Bank_Adress__c.field-meta.xml
<CustomField>
    <fullName>Bank_Adress__c</fullName>
    <label>Bank Adress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceFooter__mdt/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceFooter__mdt/fields/Beneficiary_Address__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary_Address__c</fullName>
    <label>Beneficiary Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceFooter__mdt/fields/Beneficiary_Name__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary_Name__c</fullName>
    <label>Beneficiary Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceFooter__mdt/fields/Swift_code__c.field-meta.xml
<CustomField>
    <fullName>Swift_code__c</fullName>
    <label>Swift code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/RH_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Invoice__c/fields/RH_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>RH_Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_DueDate__c.field-meta.xml
<CustomField>
    <fullName>RH_DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>RH_InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_InvoiceItem_Sum__c.field-meta.xml
<CustomField>
    <fullName>RH_InvoiceItem_Sum__c</fullName>
    <label>InvoiceItem Sum</label>
    <summarizedField>RH_Invoice_Item__c.RH_Amount__c</summarizedField>
    <summaryForeignKey>RH_Invoice_Item__c.RH_InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_Number__c.field-meta.xml
<CustomField>
    <fullName>RH_Number__c</fullName>
    <externalId>true</externalId>
    <label>Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_Po__c.field-meta.xml
<CustomField>
    <fullName>RH_Po__c</fullName>
    <label>PO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/RH_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INVOICE-ITEM{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Amount__c.field-meta.xml
<CustomField>
    <fullName>RH_Amount__c</fullName>
    <label>RH Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>RH_Currency_Symbol__c</fullName>
    <formula>CASE(RH_InvoiceId__r.RH_Currency_Code__c,
&quot;XAF&quot;, &quot;FCFA&quot;,
&quot;EUR&quot;, &quot;€&quot;,
&quot;USD&quot;, &quot;US$&quot;,
&quot;?&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RH_Currency_Symbol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_EndDate__c.field-meta.xml
<CustomField>
    <fullName>RH_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>RH_InvoiceId__c</fullName>
    <label>Invoice</label>
    <referenceTo>RH_Invoice__c</referenceTo>
    <relationshipLabel>Invoices Items</relationshipLabel>
    <relationshipName>RH_Invoices_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>RH_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Rate__c.field-meta.xml
<CustomField>
    <fullName>RH_Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_StartDate__c.field-meta.xml
<CustomField>
    <fullName>RH_StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Title__c.field-meta.xml
<CustomField>
    <fullName>RH_Title__c</fullName>
    <formula>(IF(INCLUDES( RH_description_fields__c , &apos;RH_ProjectId__c&apos;),  RH_ProjectId__r.Name +&apos; &apos;, &apos;&apos;)+
IF(INCLUDES( RH_description_fields__c , &apos;RH_Ressource__c&apos;),  RH_Ressource__r.LastName +&apos; &apos;+RH_Ressource__r.FirstName +&apos; &apos; , &apos;&apos;) +
IF(INCLUDES( RH_description_fields__c , &apos;RH_Subject__c&apos;), RH_Subject__c +&apos; &apos; , &apos;&apos;))</formula>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RH_PDF_Invoice_Controller.cls
public without sharing class RH_PDF_Invoice_Controller {
    private static RH_Invoice_Query invoiceQry = RH_Invoice_Query.getInstance();
    public HeaderWrapDatas getHeaderSettingvalue{get;set;}
    public footerWrapDatas getFooterSettingvalue {get;set;}
    public invoiceWrapper invoice{get;set;}
    static final Integer NB_PAGE_SIZE =5;
    static final Integer NB_FISRTPAGE_SIZE =7;
    static final Integer NB_PAGE_SIZE_NO_FOOTER =10;
    static final Integer NB_PAGE_SIZE_NOTHING =15;
    static final Boolean ALWAYS_HEADER =true;
    static final Boolean ALWAYS_FOOTER =false;
    public List<lineBlock> blocks{get;set;}


    
    public RH_PDF_Invoice_Controller() {
        string recordId = ApexPages.currentPage().getParameters().get('key'); 
        System.debug(' @@record id'+recordId);
        generatpageHeader__mdt getHeaderSettingvalue =[Select CompanyId__c,CompanyName__c,Phone__c,Place__c,PoBox__c,TaxId__c from generatpageHeader__mdt];
        this.getHeaderSettingvalue =buildHeader(getHeaderSettingvalue);
        System.debug('RH_PDF_Invoice_Controller  getHeaderSettingvalue: '+getHeaderSettingvalue);
        InvoiceFooter__mdt footer =[Select Acct_No_with_UBA__c,Bank_Adress__c,Bank_Name__c,Beneficiary_Address__c,Beneficiary_Name__c,Branch_Name__c,IBAN__c,Swift_code__c from InvoiceFooter__mdt Limit 1];
        this.getFooterSettingvalue =buildFooter(footer);
        //BEST PRACTICES
        List<RH_Invoice__c> Invoices = invoiceQry.getInvoice(recordId);
        if (Invoices.isEmpty()) {
            throw new RH_ControllerException('002','No Invoice founded with this ID'+recordId);
        }
        RH_Invoice__c inv=Invoices[0];
        buildInvoice(inv);
      
    
    }

    public static HeaderWrapDatas buildHeader(generatpageHeader__mdt getHeaderSettingvalue){
        HeaderWrapDatas response = new HeaderWrapDatas();
        response.CompanyId=getHeaderSettingvalue?.CompanyId__c;
        response.CompanyName=getHeaderSettingvalue?.CompanyName__c;
        response.Phone=getHeaderSettingvalue?.Phone__c;
        response.Place=getHeaderSettingvalue?.Place__c;
        response.PoBox=getHeaderSettingvalue?.PoBox__c;
        response.TaxId=getHeaderSettingvalue?.TaxId__c;

        return response;

    } 
    public static footerWrapDatas buildFooter( InvoiceFooter__mdt footer){
        footerWrapDatas response = new footerWrapDatas();
        response.AccountNum=footer?.Acct_No_with_UBA__c;
        response.BankAdress=footer?.Bank_Adress__c;
        response.BankName=footer?.Bank_Name__c;
        response.BeneficiaryAddress=footer?.Beneficiary_Address__c;
        response.BeneficiaryName=footer?.Beneficiary_Name__c;
        response.BranchName=footer?.Branch_Name__c;
        response.IBAN=footer?.IBAN__c;
        response.SwiftCode=footer?.Swift_code__c;

        return response;

    }
    public void buildInvoice(RH_Invoice__c inv){
        invoice=new invoiceWrapper(inv.Name, inv.RH_Number__c,inv.RH_Po__c,inv.RH_InvoiceDate__c,inv.RH_DueDate__c,inv.RH_InvoiceItem_Sum__c);
        invoice.setClient(buildClient(inv.RH_Account_Id__r));
        invoice.setBlocks(buildBlockList(inv.RH_Invoices_Items__r));
    }

    public List<lineBlock> buildBlockList(List<RH_Invoice_Item__c> InvoiceItems){
        List<lineBlock> blocks = new List<lineBlock>();
        integer total_size=InvoiceItems.size();
        integer block_number=0;
        integer cnt=1;
        boolean endOfItems=true;//when empty 
        do{
            Boolean isFirst=block_number==0;
            Boolean isLast= cnt==total_size;
            Boolean showHeader=!isFirst && ALWAYS_HEADER;
            Boolean showFooter= isLast || ALWAYS_FOOTER;

            integer block_size=NB_PAGE_SIZE;//with header and footer
            if (isFirst && !showFooter ) { //first page without footer
                block_size=NB_FISRTPAGE_SIZE;
            }
            if (showHeader && !showFooter) {//only with header
                block_size=NB_PAGE_SIZE_NO_FOOTER;
            }
            if (!isFirst && !showHeader && !showFooter) { // other pages without footer and header
                block_size=NB_PAGE_SIZE_NOTHING;
            }
            integer remaining_size=InvoiceItems.size();
            block_size = block_size <= remaining_size ? block_size : remaining_size;

            lineBlock block = new lineBlock(showHeader,new List<lineItem> (),showFooter);

            for (Integer k = 0; k < block_size; k++) {
                block.items.add(
                    buildLine(cnt,InvoiceItems.remove(0))//remove the item from the list, this action decrease the size of the list
                );
                cnt=cnt+1;
            }
            blocks.add(block);
            block_number=block_number+1; 
            endOfItems=(block_size >= remaining_size);
            block.showFooter= block.showFooter || endOfItems;//recaculate show footer
        }while (!endOfItems) ;

        return blocks;
    }
    public static clientWrapper buildClient(Account acc){
        clientWrapper client = new clientWrapper(acc.RH_Via__c,acc.RH_NumeroCivico__c,acc.RH_Cap__c,acc.RH_Citta__c,acc.RH_Regione__c,acc.Phone,acc.RH_Email__c,acc.RH_Piva__c,acc.RH_SDI__c,acc.Name);
        return client;
    }
    public static lineItem buildLine(integer cnt,RH_Invoice_Item__c Item){
        return new lineItem(cnt,item?.RH_Amount__c, item?.RH_Title__c, item?.RH_StartDate__c, item?.RH_EndDate__c,
            item?.RH_Quantity__c, item?.RH_Rate__c, item?.Name, item?.RH_Currency_Symbol__c);
    }
    public class lineBlock{
        public Boolean showHeader{get;set;}
        public Boolean showFooter{get;set;}
        public List<lineItem> items{get;set;}

        public lineBlock( Boolean showHeader,List<lineItem> lineItems,Boolean showFt){
            this.showHeader = showHeader;
            this.items =lineItems;
            this.showFooter =showFt;
        }
    }
    public class lineItem{
        //Invoice
        public Decimal Amount{get;set;} 
        public String Description{get;set;}
        public Date StartDate{get;set;}
        public Date EndDate{get;set;}
        public Decimal Quantity{get;set;}
        public Decimal Rate{get;set;}
        public String Name{get;set;}
        public String CurrencySymbol{get;set;}
        public integer cnt{get;set;}

        
        public lineItem(integer cnt,Decimal Amount,String Description,Date StartDate,Date EndDate,Decimal Quantity,Decimal Rate,String Name,String CurrencySymbol){
            this.cnt=cnt;
            this.Amount=Amount;
            this.Description=Description;
            this.StartDate=StartDate;
            this.EndDate=EndDate;
            this.Quantity=Quantity;
            this.Rate=Rate;
            this.Name=Name;
            this.CurrencySymbol=CurrencySymbol;
        }
        //public String RHInvoiceId{get;set;}
    }
    public class clientWrapper{
        public String Via{get;set;}
        public Decimal NumeroCivico{get;set;}
        public String Cap{get;set;}
        public String Citta{get;set;}
        public String Regione{get;set;}
        public String Phone{get;set;}
        public String Email{get;set;}
        public String Piva{get;set;}
        public String SDI{get;set;}
        public String Name{get;set;}
        public clientWrapper(String Via,Decimal NumeroCivico,String Cap,String Citta,String Regione,String Phone,String Email,String Piva,String SDI,String Name){
            this.Via=Via;
            this.NumeroCivico=NumeroCivico;
            this.Cap=Cap;
            this.Citta=Citta;
            this.Regione=Regione;
            this.Phone=Phone;
            this.Email=Email;
            this.Piva=Piva;
            this.SDI=SDI;
            this.Name=Name;
        }
    }
    public class invoiceWrapper{
        //Invoice
        public String invNumber {get;set;}
        public Date invDate{get;set;}
        public String invPo{get;set;}
        public Date invDueDate{get;set;}
        public String invName{get;set;}
        public String CurrencySymbol{get;set;}
        public Decimal invTotal{get;set;}
        public clientWrapper client{get;set;}
        public List<lineBlock> blocks{get;set;}

        public invoiceWrapper(String invName,String invNumber,String invPo,Date invDate,Date invDueDate,Decimal invTotal){
            this.invNumber=invNumber;
            this.invDate=invDate;
            this.invPo=invPo;
            this.invDueDate=invDueDate;
            this.invName=invName;
            this.invTotal=invTotal;
        }
        public void setBlocks(List<lineBlock> blocks){
            this.blocks=blocks;
            if (!blocks.isEmpty() && !blocks[0].items.isEmpty()) {
                this.CurrencySymbol=blocks[0].items[0].CurrencySymbol;
            }
        }
        public void setClient(clientWrapper client){
            this.client=client;
        }
    }

     public class footerWrapDatas{
        //footer 
        public Decimal AccountNum{get;set;}
        public String BankAdress{get;set;}
        public String BankName{get;set;}
        public String BeneficiaryAddress{get;set;}
        public String BeneficiaryName{get;set;}
        public String BranchName{get;set;}
        public String IBAN{get;set;}
        public String SwiftCode{get;set;}
     }

    public class HeaderWrapDatas{
        //getHeaderSettingvalue
        public String CompanyId{get;set;}
        public String CompanyName{get;set;}
        public String Phone{get;set;}
        public String Place{get;set;}
        public String PoBox{get;set;}
        public String TaxId{get;set;}
    }
    

}