force-app/main/default/objects/Contact/fields/RH_Extra_Infos__c.field-meta.xml
<CustomField>
    <fullName>RH_Extra_Infos__c</fullName>
    <defaultValue>&apos;[]&apos;</defaultValue>
    <description>&apos;[
    {
        &quot;label&quot;: &quot;website&quot;,
        &quot;value&quot;: &quot;www.mywebsite.com&quot;,
        &quot;name&quot;: &quot;website&quot;
    }
]&apos;</description>
    <inlineHelpText>Enter informations inthis way 
&apos;[
    {
        &quot;label&quot;: &quot;website&quot;,
        &quot;value&quot;: &quot;www.mywebsite.com&quot;,
        &quot;name&quot;: &quot;website&quot;
    }</inlineHelpText>
    <label>Extra Informations</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RH_Role__c.field-meta.xml
<CustomField>
    <fullName>RH_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Team Leader</fullName>
            </value>
            <value>
                <fullName>Base User</fullName>
            </value>
            <value>
                <fullName>Ressource Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/RH_User__c.field-meta.xml
<CustomField>
    <fullName>RH_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RH User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User Most be have the profile Custom Identity User</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Custom Identity User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RH_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/RH_ContactId__c.field-meta.xml
<CustomField>
    <fullName>RH_ContactId__c</fullName>
    <label>Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RH_Profile.cls
public  class RH_Profile {
    public RH_Profile() {
    }
    @AuraEnabled
    public static Map<string,object> getMyProfile() {
        Map<string,object> mapReturn = new Map<String, Object>();
        User u= [SELECT id,Name,Username,RH_ContactId__c FROM User WHERE Id=: Userinfo.getUserId()];
        mapReturn.put('user', u);
        mapReturn.put('error', false);
        if (String.isBlank(u?.RH_ContactId__c)) {
                mapReturn.put('error', true);
                mapReturn.put('msg','Missing Contact');
                return mapReturn;
        }
        Contact userContact=[SELECT LastName,AccountId,RH_Role__c, FirstName,RH_User__c,Email,MailingCity,Languages__c,RH_Extra_Infos__c FROM Contact WHERE Id=:u.RH_ContactId__c];
        mapReturn.put('contact', userContact);
        return mapReturn;
    }
    @AuraEnabled
    public static Map<String,Object> newUser(String contactjson){
        Map<String, Object> mapReturn = new Map<String, Object>();
        mapReturn.put('error',false);
        try {
            mapReturn.put('input',contactjson);  
            contactdetailswrapper contactinfo = (contactdetailswrapper) JSON.deserialize(contactjson, contactdetailswrapper.class);
            contact conctactUser =contactinfo.getcontact();
            conctactUser.recordTypeId=RH_Constans.RH_CONTACT_RT;
            mapReturn.put('conctactUser',conctactUser);
            //insert conctactUser;
        } catch(Exception e) {
            System.debug(e.getMessage());
            mapReturn.put('error',true);
            mapReturn.put('msg',e.getMessage());
            mapReturn.put('e',e);
        }
       
        return mapReturn;
    }
    @AuraEnabled
    public static Map<String,Object> changeMyPassword(String changepasswordjson){
        Map<String, Object> mapReturn = new Map<String, Object>();
        mapReturn.put('error',false);
        try {
            mapReturn.put('input',changepasswordjson);
            changepasswordwrapper pwdResetter = (changepasswordwrapper) JSON.deserialize(changepasswordjson, changepasswordwrapper.class);
            PageReference pr=pwdResetter.changePassword();
            // String newPassword='0037Q000007I2h0QACwqaa';
            // String verifyNewPassword='0037Q000007I2h0QACwqaa';
            // String oldpassword='0037Q000007I2h0QACwqa'; 
            mapReturn.put('Ok',true);
            mapReturn.put('prUrl',pr.getUrl());
            //coninsert conctactUser;
        } catch(Exception e) {
            System.debug(e.getMessage());
            mapReturn.put('error',true);
            mapReturn.put('msg',e.getMessage());
            mapReturn.put('e',e);
        }
        return mapReturn;
    }
    public class contactdetailswrapper  {
        @AuraEnabled public String LastName;
        @AuraEnabled public String FirstName;
        @AuraEnabled public String Email;
        public Contact getcontact() {
            return new Contact(
                lastname=this.lastname, 
                firstname=this.firstname, 
                email=this.email);
        }
    }
    public class changepasswordwrapper  {
        @AuraEnabled public String newPassword;
        @AuraEnabled public String verifyNewPassword;
        @AuraEnabled public String oldpassword;
        public PageReference changePassword() {
            return Site.changePassword(newPassword, verifyNewPassword, oldpassword);
        }
    }
}