force-app/main/default/objects/Contact/fields/RH_Status__c.field-meta.xml
<CustomField>
    <fullName>RH_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Banned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/RH_Accomplishment__c.object-meta.xml
<CustomObject>
    <label>Accomplishment</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Accomplishment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accomplishments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Date__c.field-meta.xml
<CustomField>
    <fullName>RH_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Description__c.field-meta.xml
<CustomField>
    <fullName>RH_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Status__c.field-meta.xml
<CustomField>
    <fullName>RH_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Submiter__c.field-meta.xml
<CustomField>
    <fullName>RH_Submiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submiter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accomplishments</relationshipLabel>
    <relationshipName>Accomplishments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Title__c.field-meta.xml
<CustomField>
    <fullName>RH_Title__c</fullName>
    <label>Title</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Visibility__c.field-meta.xml
<CustomField>
    <fullName>RH_Visibility__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Visibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/RH_ContactId__c.field-meta.xml
<CustomField>
    <fullName>RH_ContactId__c</fullName>
    <label>Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RH_Accomplishment_Controller.cls
public without sharing class RH_Accomplishment_Controller {
    
    private static RH_Accomplishment_Query accomQry = RH_Accomplishment_Query.getInstance();
    private static RH_User_Query userQry = RH_User_Query.getInstance();

    @AuraEnabled
    public static List<RH_Accomplishment__c> getAccomplishment(){
        return accomQry.getAccomplishmentList();
    }

    @AuraEnabled
    public static RH_Accomplishment__c accomplishmentDetail(String idAccom){
        return accomQry.getAccomplishmentById(idAccom);
    }

    @AuraEnabled
    public static Boolean checkCurrentContact(String idAcc){
        RH_Accomplishment__c accom =  accomQry.getAccomplishmentById(idAcc);
        List<User> currentU = userQry.getUserById(UserInfo.getUserId());
        if (currentU.size() > 0){
            if(accom.RH_Submiter__c == currentU[0].RH_ContactId__c){
                return true;
            }else{
                return false;
            }  
        }else{
            return false;
        }
    }

    @AuraEnabled
    public static Map<String,Object> addAccomplishment(String accomJson, String status){
        Map<String, Object> mapReturn = new Map<String, Object>();
        mapReturn.put('error',false);
        try {
            mapReturn.put('input',accomJson);  
            Accomplishmentdetailswrapper accomInfo = (Accomplishmentdetailswrapper) JSON.deserialize(accomJson, Accomplishmentdetailswrapper.class);
            RH_Accomplishment__c accomplish =accomInfo.accomplishmentTake();
            accomplish.RH_Status__c = status;
            List<User> currentU = userQry.getUserById(UserInfo.getUserId());
            if (currentU.size() > 0) {
                accomplish.RH_Submiter__c = currentU[0].RH_ContactId__c;
                insert accomplish;   
            }else{
                throw new RH_ControllerException('002','No RH Contact Founded');
            }
        } catch(Exception e) {
            System.debug(e.getMessage());
            mapReturn.put('error',true);
            mapReturn.put('msg',e.getMessage());
            mapReturn.put('e',e);
        }
       
        return mapReturn;
    }

    public class Accomplishmentdetailswrapper {
        @AuraEnabled public String description;
        @AuraEnabled public String title;
        @AuraEnabled public Boolean visibility;
        @AuraEnabled public Date myDate;
        public RH_Accomplishment__c accomplishmentTake() {
            return new RH_Accomplishment__c(
                RH_Description__c=this.description, 
                RH_Title__c = this.title,
                RH_Visibility__c=this.visibility,
                RH_Date__c=this.myDate
            );
        }
    }
}