force-app/main/default/objects/Contact/fields/RH_Status__c.field-meta.xml
<CustomField>
    <fullName>RH_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Banned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/RH_Accomplishment__c.object-meta.xml
<CustomObject>
    <label>Accomplishment</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Accomplishment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accomplishments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Date__c.field-meta.xml
<CustomField>
    <fullName>RH_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Description__c.field-meta.xml
<CustomField>
    <fullName>RH_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Status__c.field-meta.xml
<CustomField>
    <fullName>RH_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Submiter__c.field-meta.xml
<CustomField>
    <fullName>RH_Submiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submiter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accomplishments</relationshipLabel>
    <relationshipName>Accomplishments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Title__c.field-meta.xml
<CustomField>
    <fullName>RH_Title__c</fullName>
    <label>Title</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Accomplishment__c/fields/RH_Visibility__c.field-meta.xml
<CustomField>
    <fullName>RH_Visibility__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Visibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RH_Accomplishment_Query.cls
public without sharing class RH_Accomplishment_Query {

    /** The class instance */
    private static RH_Accomplishment_Query instance = null;

    /**
     * @description @return the class instance
     */
    public static RH_Accomplishment_Query getInstance() {

        if(instance == null) {

            instance = new RH_Accomplishment_Query();
        }
        return instance;
    }

	public List<RH_Accomplishment__c> getAccomplishmentList() {
        return [SELECT Id, Name, RH_Description__c, Rh_Status__c, RH_Date__c, RH_Submiter__r.Name, RH_Title__c, RH_Visibility__c FROM RH_Accomplishment__c];
    }

    public RH_Accomplishment__c getAccomplishmentById(String recordId) {
        return [SELECT Id, Name, RH_Description__c, Rh_Status__c, RH_Date__c, RH_Submiter__c, RH_Submiter__r.Name, RH_Title__c, RH_Visibility__c FROM RH_Accomplishment__c WHERE Id = :recordId LIMIT 1];
    }
}