force-app/main/default/objects/Contact/fields/RH_Status__c.field-meta.xml
<CustomField>
    <fullName>RH_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Banned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Request__c/RH_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Request__c/fields/RH_Addressed_To__c.field-meta.xml
<CustomField>
    <fullName>RH_Addressed_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Addressed To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests (Addressed To)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Request__c/fields/RH_Description__c.field-meta.xml
<CustomField>
    <fullName>RH_Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RH_Request__c/fields/RH_RequestTypeName__c.field-meta.xml
<CustomField>
    <fullName>RH_RequestTypeName__c</fullName>
    <label>Request Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Request__c/fields/Rh_Status__c.field-meta.xml
<CustomField>
    <fullName>Rh_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submited</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RH_Request_Query.cls
public class RH_Request_Query {
     /** The class instance */
    private static RH_Request_Query instance = null;

    /**
     * @description @return the class instance
     */
    public static RH_Request_Query getInstance() {

        if(instance == null) {

            instance = new RH_Request_Query();
        }
        return instance;
    }

	public List<RH_Request__c> getLastrequest(Integer edLimit) {
        return [SELECT id,Name,RH_Description__c,Rh_Status__c,RH_Addressed_To__r.Name,RecordType.Name ,CreatedDate,RH_RequestTypeName__c FROM RH_Request__c WHERE ownerId =: UserInfo.getUserId() order by createddate asc limit : edLimit ];
    }
}