force-app/main/default/objects/Contact/fields/RH_User__c.field-meta.xml
<CustomField>
    <fullName>RH_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RH User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User Most be have the profile Custom Identity User</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Custom Identity User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>RH_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Invoice__c/RH_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Invoice__c/fields/RH_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>RH_Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_DueDate__c.field-meta.xml
<CustomField>
    <fullName>RH_DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>RH_InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_InvoiceItem_Sum__c.field-meta.xml
<CustomField>
    <fullName>RH_InvoiceItem_Sum__c</fullName>
    <label>InvoiceItem Sum</label>
    <summarizedField>RH_Invoice_Item__c.RH_Amount__c</summarizedField>
    <summaryForeignKey>RH_Invoice_Item__c.RH_InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_Name__c.field-meta.xml
<CustomField>
    <fullName>RH_Name__c</fullName>
    <formula>CASE( MONTH(RH_InvoiceDate__c ), 1, &apos;January&apos;,2, &apos;February&apos;,3, &apos;March&apos;,4, &apos;April&apos;,5, &apos;May&apos;,6, &apos;June&apos;,7, &apos;	July&apos;,
        8, &apos;August&apos;,9, &apos;September&apos;,10, &apos;October&apos;,11, &apos;November&apos;,12, &apos;December&apos;,&apos;NONE&apos;	) +&apos;-&apos;+  TEXT(YEAR(RH_InvoiceDate__c))</formula>
<formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
<label>Title</label>
<type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Invoice__c/fields/RH_Po__c.field-meta.xml
<CustomField>
    <fullName>RH_Po__c</fullName>
    <label>PO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/RH_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INVOICE-ITEM{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Amount__c.field-meta.xml
<CustomField>
    <fullName>RH_Amount__c</fullName>
    <label>RH Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>RH_Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XAF</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
                <default>true</default>
                <label>EUR</label>
            </value>
            <value>
                <fullName>US$</fullName>
                <isActive>false</isActive>
                <label>US$</label>
            </value>
            <value>
                <fullName>€</fullName>
                <isActive>false</isActive>
                <label>€</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_EndDate__c.field-meta.xml
<CustomField>
    <fullName>RH_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Holiday__c.field-meta.xml
<CustomField>
    <fullName>RH_Holiday__c</fullName>
    <label>Holiday</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>RH_InvoiceId__c</fullName>
    <label>Invoice</label>
    <referenceTo>RH_Invoice__c</referenceTo>
    <relationshipLabel>Invoices Items</relationshipLabel>
    <relationshipName>RH_Invoices_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_ProjectId__c.field-meta.xml
<CustomField>
    <fullName>RH_ProjectId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices Items</relationshipLabel>
    <relationshipName>RH_Invoices_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>RH_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Rate__c.field-meta.xml
<CustomField>
    <fullName>RH_Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_Ressource__c.field-meta.xml
<CustomField>
    <fullName>RH_Ressource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ressource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices Items</relationshipLabel>
    <relationshipName>RH_Invoices_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Invoice_Item__c/fields/RH_StartDate__c.field-meta.xml
<CustomField>
    <fullName>RH_StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TimeSheet/fields/RH_Approver__c.field-meta.xml
<CustomField>
    <fullName>RH_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Sheets (Approver)</relationshipLabel>
    <relationshipName>RH_TimeSheetsToHandle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeSheet/fields/RH_Name__c.field-meta.xml
<CustomField>
    <fullName>RH_Name__c</fullName>
    <formula>CASE( MONTH(StartDate ), 1, &apos;January&apos;,2, &apos;February&apos;,3, &apos;March&apos;,4, &apos;April&apos;,5, &apos;May&apos;,6, &apos;June&apos;,7, &apos;	July&apos;,
							8, &apos;August&apos;,9, &apos;September&apos;,10, &apos;October&apos;,11, &apos;November&apos;,12, &apos;December&apos;,&apos;NONE&apos;	) +&apos;-&apos;+  TEXT(YEAR(StartDate))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSheet/fields/RH_NoteApprover__c.field-meta.xml
<CustomField>
    <fullName>RH_NoteApprover__c</fullName>
    <label>Note ( Approver )</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeSheet/fields/RH_Submiter__c.field-meta.xml
<CustomField>
    <fullName>RH_Submiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submiter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Sheets</relationshipLabel>
    <relationshipName>RH_TimeSheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeSheet/fields/RH_Total_Free_Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>RH_Total_Free_Duration_Hours__c</fullName>
    <formula>RH_Total_Free_Duration_Minutes__c / 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Free Duration (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeSheet/fields/RH_Total_Free_Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>RH_Total_Free_Duration_Minutes__c</fullName>
    <label>Total Free Duration (Minutes)</label>
    <summarizedField>TimeSheetEntry.DurationInMinutes</summarizedField>
    <summaryFilterItems>
        <field>TimeSheetEntry.Type</field>
        <operation>equals</operation>
        <value>Free</value>
    </summaryFilterItems>
    <summaryForeignKey>TimeSheetEntry.TimeSheetId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RH_Invoice_Query.cls
public without sharing class RH_Invoice_Query {
    /** The class instance */
    private static RH_Invoice_Query instance = null;

    /**
     * @description @return the class instance
     */
    public static RH_Invoice_Query getInstance() {

        if(instance == null) {

            instance = new RH_Invoice_Query();
        }
        return instance;
    }
    /** The class methods need to be replace with the coresponding of invoice object*/

    public List<TimeSheet> getUserTimeSheets(String userId) {
        return [SELECT Id,RH_Name__c,TimeSheetNumber,TotalDurationInHours,TotalDurationInMinutes,TimeSheetEntryCount, EndDate, StartDate,toLabel(Status) StatusLabel,Status,OwnerId,Owner.Name,RH_NoteApprover__c,
                RH_Approver__r.Account.Name,RH_Approver__r.Name,RH_Approver__r.RH_User__c ,
                (SELECT Id,Subject,TimeSheetEntryNumber, Description,DurationInMinutes, RH_Project__c,RH_Project__r.Name, StartTime, EndTime,Status,CreatedDate,TimeSheetId FROM TimeSheetEntries) FROM TimeSheet WHERE OwnerId =:userId];
    }
    public List<TimeSheet> getMyTimeSheets() {
        return getUserTimeSheets(UserInfo.getUserId());
    }
    public List<TimeSheet> getTimeSheet(String timesheetId) {
        return [SELECT Id,TimeSheetNumber,TotalDurationInHours,TotalDurationInMinutes,TimeSheetEntryCount, EndDate, StartDate,toLabel(Status) StatusLabel,Status,OwnerId,Owner.Name,RH_NoteApprover__c,
        RH_Total_Free_Duration_Minutes__c,	RH_Total_Free_Duration_Hours__c, RH_Name__c,       
        RH_Submiter__r.Account.Name,RH_Submiter__r.Account.Phone,RH_Submiter__r.Account.Type,RH_Submiter__r.Account.Website,RH_Submiter__r.Account.Owner.Name ,
                RH_Approver__r.Account.Name,RH_Approver__r.Name,RH_Approver__r.RH_User__c ,
                (SELECT Id,Subject,TimeSheetEntryNumber, Description,DurationInMinutes, RH_Project__c,RH_Project__r.Name, StartTime, EndTime,Status,CreatedDate,TimeSheetId,RH_Optional__c FROM TimeSheetEntries) FROM TimeSheet WHERE Id =:timesheetId];
    }
    public List<TimeSheet> getAllTimeSheet() {
        return [SELECT Id,RH_Name__c,TimeSheetNumber,TotalDurationInHours,TotalDurationInMinutes,TimeSheetEntryCount, EndDate, StartDate,toLabel(Status) StatusLabel,Status,OwnerId,Owner.Name, 
                (SELECT Id,Subject,TimeSheetEntryNumber, Description,DurationInMinutes, RH_Project__c,RH_Project__r.Name, StartTime, EndTime,Status,CreatedDate,TimeSheetId FROM TimeSheetEntries) FROM TimeSheet ];
    }
    public List<TimeSheet> getUserTodayTimeSheets(String userId) {
        return [SELECT Id,RH_Name__c,TimeSheetNumber,TotalDurationInHours,TotalDurationInMinutes,TimeSheetEntryCount, EndDate, StartDate,toLabel(Status) StatusLabel,Status,OwnerId,Owner.Name FROM TimeSheet 
        WHERE StartDate = THIS_MONTH];
    }
    public List<RH_Invoice__c> getInvoice(String invoiceId) {
        return [SELECT Id,Name,RH_Name__c,RH_DueDate__c,RH_InvoiceDate__c,RH_Po__c, OwnerId, RH_InvoiceItem_Sum__c, 
                        RH_Account_Id__r.Name,RH_Account_Id__r.Phone,RH_Account_Id__r.Type,RH_Account_Id__r.Website, 
                (SELECT Id,RH_StartDate__c,RH_EndDate__c, Name, RH_Quantity__c,RH_Rate__c,RH_Amount__c,RH_Holiday__c,RH_Currency_Code__c, toLabel(RH_Currency_Code__c) currency,RH_InvoiceId__c,
                RH_ProjectId__r.Name, RH_ProjectId__r.Is_Effective__c, RH_ProjectId__r.RH_Account_ID__c,
                RH_Ressource__r.Name,RH_Ressource__r.RH_User__c FROM RH_Invoices_Items__r) 
                FROM 	RH_Invoice__c WHERE Id =:invoiceId];
    }
    public  Map<Id,RH_Invoice__c> getFilteredInvoices(RH_Invoice_Controller.InvoiceFilterWrapper filter){
        
        Date startdate=filter.startdate;
        Date enddate=filter.enddate;
        String ordBy=String.isNotBlank(filter.orderBy)?filter.orderBy: ' CreatedDate ' ;
        String ordOn= String.isNotBlank(filter.orderOn)?filter.orderOn: ' DESC ';

        String query = 'SELECT Id,Name,RH_Name__c,RH_Account_Id__r.Name,RH_DueDate__c,RH_InvoiceDate__c,RH_Po__c,'
        +'CreatedDate FROM RH_Invoice__c '; 
        
        String queryWhere = ' Where RH_Account_Id__c != Null ';
        
        
        if(startdate != null){
			queryWHERE = queryWHERE + ' AND (RH_InvoiceDate__c >= : startdate) ';
		}
        if(enddate != null){
			queryWHERE = queryWHERE + ' AND (RH_DueDate__c <= : enddate) ';
		}
        String queryORDER='';
        if(String.isNotBlank(ordBy)){

			queryORDER = queryORDER + ' Order by '+ordBy+' '+ordOn;
		}
        
        query= query+queryWHERE+queryORDER;

        Map<Id, RH_Invoice__c> invoicesMap=new Map<Id, RH_Invoice__c>((List<RH_Invoice__c>) Database.query(query));
        
        return invoicesMap;
    }
}