force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
   
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Event Hoder</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>My Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/RH_ContactId__c.field-meta.xml
<CustomField>
    <fullName>RH_ContactId__c</fullName>
    <label>Contact Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RH_EventControllerTest.cls
@isTest
public with sharing class RH_EventControllerTest {
    @testSetup
    static void setup() {
        Contact con = new Contact(LastName='Ndon',FirstName='Will');
        insert con;
        User u = new User(
            Username='autoproc@00d7q000005ytvlua0',
            LastName='Process',
            RH_ContactId__c=con.Id);
        insert u;
        Event__c ev = new Event__c(Name='Azerty',
                                   Contact_Id__c=u.RH_ContactId__c,
                                   Description__c='description',
                                   Start_Date__c=system.Today()+1,
                                   Status__c='Draft'
                                   );
        insert ev;
    }

    @isTest static void TestgetEventList(){
        List<Event__c> events = RH_EventController.getEventList();
    }
    @isTest static void TestgetEvent(){
        Event__c e = [Select Id From Event__c];
        Event__c events = RH_EventController.getEvent(e.Id);
    }
}