force-app/main/default/objects/News__c/News__c.object-meta.xml
<CustomObject>
    <label>News</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/News__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RH_News_Query.cls
public class RH_News_Query {

     /** The class instance */
     private static RH_News_Query instance = null;

     /**
      * @description @return the class instance
      */
     public static RH_News_Query getInstance() {
 
         if(instance == null) {
             instance = new RH_News_Query();
         }
         return instance;
     }
 

    public List<News__c> getActiveNews() {
        String query = 'SELECT Id, Name, Description__c,IsActive__c,Image__c FROM News__c WHERE IsActive__c = TRUE';
        return Database.query(query);
    }
    
    public List<News__c> getAllNews() {
        return [SELECT Id, Name, Description__c,IsActive__c,Image__c FROM News__c];
    }

    public News__c getNewsById(String recordId){
        List<News__c> newsList= [SELECT Id, Name, Description__c,IsActive__c,Image__c FROM News__c WHERE Id =: recordId ];
        return newsList[0] ;
    }
 
}